version: '3.8'

services:
  # OpenTelemetry Collector for local development
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.112.0
    container_name: otel-collector
    command: ["--config-file=/etc/otelcol-contrib/config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml:ro
    ports:
      - "4317:4317"   # OTLP gRPC receiver
      - "4318:4318"   # OTLP HTTP receiver
      - "13133:13133" # Health check extension
      - "55679:55679" # zpages extension
    networks:
      - otel-network

  # Jaeger UI for viewing traces (optional)
  jaeger:
    image: jaegertracing/all-in-one:1.62
    container_name: jaeger
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "16686:16686" # Jaeger UI
      - "14250:14250" # accept model.proto
      - "14268:14268" # accept jaeger.thrift directly from clients
    networks:
      - otel-network
    depends_on:
      - otel-collector

networks:
  otel-network:
    driver: bridge
