// This file is auto-generated by @hey-api/openapi-ts

export const AuthErrorResponseSchema = {
    type: 'object',
    properties: {
        message: {
            type: 'string',
            nullable: true
        }
    },
    additionalProperties: false
} as const;

export const AuthSuccessResponseSchema = {
    type: 'object',
    properties: {
        token: {
            type: 'string',
            nullable: true
        },
        userId: {
            type: 'integer',
            format: 'int32'
        },
        username: {
            type: 'string',
            nullable: true
        }
    },
    additionalProperties: false
} as const;

export const LoginRequestSchema = {
    type: 'object',
    properties: {
        username: {
            type: 'string',
            nullable: true
        },
        password: {
            type: 'string',
            nullable: true
        }
    },
    additionalProperties: false
} as const;

export const RandomPokemonDtoSchema = {
    type: 'object',
    properties: {
        name: {
            type: 'string',
            nullable: true
        },
        type: {
            type: 'string',
            nullable: true
        },
        image: {
            type: 'string',
            nullable: true
        }
    },
    additionalProperties: false
} as const;

export const RegisterRequestSchema = {
    type: 'object',
    properties: {
        username: {
            type: 'string',
            nullable: true
        },
        email: {
            type: 'string',
            nullable: true
        },
        password: {
            type: 'string',
            nullable: true
        }
    },
    additionalProperties: false
} as const;

export const WeatherForecastDtoSchema = {
    type: 'object',
    properties: {
        date: {
            type: 'string',
            format: 'date'
        },
        temperatureC: {
            type: 'integer',
            format: 'int32'
        },
        summary: {
            type: 'string',
            nullable: true
        },
        temperatureF: {
            type: 'integer',
            format: 'int32',
            readOnly: true
        }
    },
    additionalProperties: false
} as const;

export const WeatherForecastDtoWritableSchema = {
    type: 'object',
    properties: {
        date: {
            type: 'string',
            format: 'date'
        },
        temperatureC: {
            type: 'integer',
            format: 'int32'
        },
        summary: {
            type: 'string',
            nullable: true
        }
    },
    additionalProperties: false
} as const;
