// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, Client, TDataShape } from './client';
import type { PostAuthLoginData, PostAuthLoginResponses, PostAuthLoginErrors, PostAuthRegisterData, PostAuthRegisterResponses, PostAuthRegisterErrors } from './types.gen';
import { zPostAuthLoginData, zPostAuthLoginResponse, zPostAuthRegisterData, zPostAuthRegisterResponse } from './zod.gen';
import { client } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Authenticate a user
 * Validates credentials and returns a JWT
 */
export const postAuthLogin = <ThrowOnError extends boolean = false>(options: Options<PostAuthLoginData, ThrowOnError>) => {
    return (options.client ?? client).post<PostAuthLoginResponses, PostAuthLoginErrors, ThrowOnError>({
        requestValidator: async (data) => {
            return await zPostAuthLoginData.parseAsync(data);
        },
        responseValidator: async (data) => {
            return await zPostAuthLoginResponse.parseAsync(data);
        },
        url: '/auth/login',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Register a new user
 * Creates a new user account and returns a JWT
 */
export const postAuthRegister = <ThrowOnError extends boolean = false>(options: Options<PostAuthRegisterData, ThrowOnError>) => {
    return (options.client ?? client).post<PostAuthRegisterResponses, PostAuthRegisterErrors, ThrowOnError>({
        requestValidator: async (data) => {
            return await zPostAuthRegisterData.parseAsync(data);
        },
        responseValidator: async (data) => {
            return await zPostAuthRegisterResponse.parseAsync(data);
        },
        url: '/auth/register',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};
