// This file is auto-generated by @hey-api/openapi-ts

import { z } from 'zod';

export const zAuthErrorResponse = z.object({
    message: z.optional(z.string())
});

export const zAuthSuccessResponse = z.object({
    token: z.optional(z.string()),
    userId: z.optional(z.int()),
    username: z.optional(z.string())
});

export const zLoginRequest = z.object({
    password: z.optional(z.string()),
    username: z.optional(z.string())
});

export const zRandomPokemonResponse = z.object({
    image: z.optional(z.string()),
    name: z.optional(z.string()),
    type: z.optional(z.string())
});

export const zRegisterRequest = z.object({
    email: z.optional(z.string()),
    password: z.optional(z.string()),
    username: z.optional(z.string())
});

export const zGetRandomPokemonData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zGetRandomPokemonResponse = zRandomPokemonResponse;

export const zPostAuthLoginData = z.object({
    body: zLoginRequest,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zPostAuthLoginResponse = zAuthSuccessResponse;

export const zPostAuthRegisterData = z.object({
    body: zRegisterRequest,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zPostAuthRegisterResponse = zAuthSuccessResponse;
