#!/usr/bin/env sh

# Source nvm to make npm available
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

echo "🔍 Running Prettier formatter..."
(cd MySvelteApp.Client && npm run format)

echo "🔍 Running Go formatter..."
(cd MySvelteApp.Server && go fmt ./...)
