apiVersion: 1

datasources:
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    isDefault: true
    jsonData:
      derivedFields:
        - name: TraceID
          matcherRegex: "traceID=(\\w+)"
          url: "http://jaeger:16686/trace/$${__value.raw}"
  - name: Jaeger
    type: jaeger
    access: proxy
    url: http://jaeger:16686

